"""
Unsloth-based fine-tuning for Gemma-4 26B MoE SAR Mastermind.

Trains the model to perform strategic triage and orchestration for 
Search and Rescue missions using simulated crisis datasets.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

import torch
from datasets import load_dataset
from trl import SFTTrainer, SFTConfig
from unsloth import FastVisionModel
from unsloth.trainer import UnslothVisionDataCollator

logger = logging.getLogger(__name__)

def finetune_sar_mastermind(
    model_id: str = "unsloth/gemma-4-26b-a4b-it",
    dataset_path: str = "data/sar_training_vlm.jsonl",
    output_dir: str = "artifacts/mastermind_sar_lora",
    epochs: int = 3,
    batch_size: int = 2,
    gradient_accumulation_steps: int = 8,
):
    # 1. Load Model and Processor
    # Gemma-4 26B MoE requires a decent amount of VRAM, but Unsloth 4-bit makes it fit in ~16GB.
    model, processor = FastVisionModel.from_pretrained(
        model_name = model_id,
        load_in_4bit = True,
        use_gradient_checkpointing = "unsloth",
    )

    # 2. Add LoRA adapters
    model = FastVisionModel.get_peft_model(
        model,
        r = 32, # Higher rank for complex strategic reasoning
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", 
                         "gate_proj", "up_proj", "down_proj"],
        lora_alpha = 64,
        lora_dropout = 0,
        bias = "none",
        random_state = 3407,
        finetune_vision_layers = False, # Keep vision tower frozen to preserve general knowledge
    )

    # 3. Load and prepare dataset
    # We use the JSONL file generated by SARScenarioGenerator
    dataset = load_dataset("json", data_files=dataset_path, split="train")

    # 4. Initialize Trainer
    # We use the specialized UnslothVisionDataCollator even if we currently focus on text
    # to maintain compatibility with the multimodal Gemma-4 architecture.
    trainer = SFTTrainer(
        model = model,
        tokenizer = processor,
        train_dataset = dataset,
        dataset_text_field = "messages", # Pointing to the OpenAI format list
        data_collator = UnslothVisionDataCollator(model, processor),
        args = SFTConfig(
            per_device_train_batch_size = batch_size,
            gradient_accumulation_steps = gradient_accumulation_steps,
            warmup_steps = 5,
            max_steps = -1, # Run for full epochs
            num_train_epochs = epochs,
            learning_rate = 2e-4,
            fp16 = not torch.cuda.is_bf16_supported(),
            bf16 = torch.cuda.is_bf16_supported(),
            logging_steps = 1,
            optim = "adamw_8bit",
            weight_decay = 0.01,
            lr_scheduler_type = "linear",
            seed = 3407,
            output_dir = output_dir,
            save_strategy = "epoch",
            report_to = "none",
        ),
    )

    # 5. Execute Training
    logger.info("Starting SAR Mastermind Fine-Tuning...")
    trainer.train()

    # 6. Save final adapters
    model.save_pretrained(output_dir)
    processor.save_pretrained(output_dir)
    logger.info("SAR Mastermind saved successfully to %s", output_dir)
